### ISSUE TITLE
Cannot find module 'passport-figma'

### ISSUE THREAD

**Issue by florianpeninon** [LiamMartens/passport-figma#1]
Hi there,

I'm trying to use this package but it looks like node can't find the module.
I've tried on a clean express app generated via their generator and it still output an error (pasted below).
```
Error: Cannot find module 'passport-figma'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Volumes/workspace/learn/passport-figma-playground/auth/figma.js:2:21)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

Any idea how to fix it?
Thanks

**Comment by LiamMartens** [comment]
How are you trying to include the package after installing?

**Comment by florianpeninon** [comment]
As mentionned on the readme:
```
var FigmaStrategy = require('passport-figma').Strategy;
```
This line by itself is enough for the freshly generated express app to throw an error.

**Comment by zyumbik** [comment]
I'm having the same problem.

**Comment by LiamMartens** [comment]
I fixed the issue with the import.

**Comment by cronnelo** [comment]
I'm getting this issue

**Comment by LiamMartens** [comment]
@cronnelo  fixed this in latest release.
